version: '3.6'

services:
  node:
    container_name: node_cbsn
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    volumes:
      - ./source:/app/source
      - ./.env:/app/.env